### ISSUE TITLE
no graphic window?

### ISSUE THREAD

**Issue by ever4cyth** [kapelner/GemIdent#1]
Hi,

I tried to figure out how to use your program but not successful. I downloaded from the github, went to executable folder and typed java -Xmx1000m -Xss2m -Xoss2m -jar gemident_v1.2.jar, a small window popups to let me choose the name of project and location, i selected orange_groove folder and the image set type was choose automatically to Non-global image set. I clicked ok and waited for long time but nothing happened, no graphic window showed up as in manual. could you please give me a hand? I used ubuntu 12.04. Thanks!

Henry

**Comment by kapelner** [comment]
Was there an error message that came up in the terminal?

**Comment by kapelner** [comment]
You may also want to try anting to compile the code to a new jar and run it
from that jar.

**Comment by ever4cyth** [comment]
Thanks for your reply. I copy the output from the terminal:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at GemIdentView.KClassInfo.getName(KClassInfo.java:382)
    at com.sun.java.swing.plaf.gtk.GTKStyle.getInsets(GTKStyle.java:315)
    at
javax.swing.plaf.synth.SynthStyle.installDefaults(SynthStyle.java:913)
    at
javax.swing.plaf.synth.SynthLookAndFeel.updateStyle(SynthLookAndFeel.java:264)
    at
javax.swing.plaf.synth.SynthPanelUI.updateStyle(SynthPanelUI.java:117)
    at
javax.swing.plaf.synth.SynthPanelUI.installDefaults(SynthPanelUI.java:100)
    at javax.swing.plaf.basic.BasicPanelUI.installUI(BasicPanelUI.java:56)
    at javax.swing.plaf.synth.SynthPanelUI.installUI(SynthPanelUI.java:62)
    at javax.swing.JComponent.setUI(JComponent.java:655)
    at javax.swing.JPanel.setUI(JPanel.java:153)
    at javax.swing.JPanel.updateUI(JPanel.java:126)
    at javax.swing.JPanel.<init>(JPanel.java:86)
    at javax.swing.JPanel.<init>(JPanel.java:109)
    at javax.swing.JPanel.<init>(JPanel.java:117)
    at GemIdentView.KClassInfo.<init>(KClassInfo.java:151)
    at GemIdentView.KStainInfo.<init>(KStainInfo.java:64)
    at GemIdentView.KColorTrainPanel.AddInfo(KColorTrainPanel.java:107)
    at GemIdentView.KColorTrainPanel.AddInfo(KColorTrainPanel.java:102)
    at
GemIdentView.KColorTrainPanel.DefaultPopulateBrowser(KColorTrainPanel.java:129)
    at GemIdentView.KFrame.DefaultPopulateWindows(KFrame.java:321)
    at GemIdentOperations.Run.BuildRunObjectFromDefaults(Run.java:267)
    at GemIdentOperations.Run.NewProject(Run.java:382)
    at
GemIdentView.InitScreen$ContentPane$10.actionPerformed(InitScreen.java:376)
    at
javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at
javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
    at
javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at
javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at
javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6505)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
    at java.awt.Component.processEvent(Component.java:6270)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4861)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at
java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at
java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at
java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:708)
    at java.awt.EventQueue$4.run(EventQueue.java:706)
    at java.security.AccessController.doPrivileged(Native Method)
    at
java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
    at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

also there is thumbs folder appears in the original orange_grove folder. is
it normal?

please let me know if you need more information or troubleshooting.

**Comment by kapelner** [comment]
Do a pull and it should be fixed. Unsure why that didn't work on linux but
worked on windows.

**Comment by ever4cyth** [comment]
Hi,

You also mentioned that i can compile it by myself. but i couldn't find the
buildfile for this program. is it included in the distribution?

**Comment by kapelner** [comment]
I tried to make a buildfile, but I couldn't figure out how to get all the
dependencies references and the graphics directory inside of the jar. If
you can figure it out, I can give you push access since that would be a
really nice thing to have. I've been manually building the JARs before each
release and it's not pleasant.

**Comment by kapelner** [comment]
I now made the buildfile. You can pull and run "ant." Let me know if it works for you...
